# .github/workflows/deploy.yml
name: Build & Deploy (Astro + manifest)

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write  # needed to push to gh-pages

jobs:
  build:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install ffmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Verify ffmpeg
        run: |
            which ffmpeg
            ffmpeg -version

      - name: Install deps
        run: npm ci || npm i

      - name: Generate manifest & indexes
        env:
            R2_ENDPOINTS: ${{ secrets.R2_ENDPOINTS }}
            R2_ACCESS_KEY_IDS: ${{ secrets.R2_ACCESS_KEY_IDS }}
            R2_SECRET_ACCESS_KEYS: ${{ secrets.R2_SECRET_ACCESS_KEYS }}
            R2_BUCKETS: ${{ secrets.R2_BUCKETS }}
            PUBLIC_MEDIA_BASES: ${{ secrets.PUBLIC_MEDIA_BASES }}

            R2_OBJECTS_CACHE: ${{ vars.R2_OBJECTS_CACHE }}
            R2_SKIP_LIST: ${{ vars.R2_SKIP_LIST }}

            ENABLE_LOCAL_POSTERS: ${{ vars.ENABLE_LOCAL_POSTERS }}
        run: node scripts/generate-manifest.js

      - name: Build site
        env:
            MY_PASSWORD: ${{ secrets.MY_PASSWORD }}
        run: npx astro build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
